=head1 NAME

Kappa::Example -

=head1 SYNOPSIS

  use Kappa::Example;

=head1 DESCRIPTION

Kappa::Example is

=head1 AUTHOR

Takuya Tsuchida E<lt>tsucchi {at} cpan.orgE<gt>

=head1 SEE ALSO

=head1 LICENSE

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.


=cut

